#!/bin/bash
PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin;

#info
function amh_module_info()
{
		echo 'AMH-ModuleName: AMBmail-1.0';
		echo 'AMH-ModuleDescription: AMBmail - AMH面板数据远程备份到邮箱模块。使用本模块可添加邮箱做为AMH远程备份，兼容支持所有国内外电子邮箱(163、qq、gmail、139…等)，AMBmail会自动分卷发送，备份文件大小无限制。';
		echo 'AMH-ModuleButton: 安装/卸载';
		echo 'AMH-ModuleDate: 2013-07-05';
		echo 'AMH-ModuleAdmin: ./index.php?c=AMBmail';
		echo 'AMH-ModuleWebSite: http://amysql.com';
		echo 'AMH-ModuleIco: http://amysql.com/View/images/amh_module/AMBmail.gif';
		echo 'AMH-ModuleScriptBy: Amysql';
}

#install
function amh_module_install()
{
	if amh_module_status ; then
		exit;
	else
		cd /usr/local/;
		wget http://code.amysql.com/files/mutt-1.5.21.tar.gz;
		tar -zxvf mutt-1.5.21.tar.gz;
		cd mutt-1.5.21;
		./configure;
		make && make install;

		cd /root/amh/modules/AMBmail-1.0;
		\cp ./Model/AMBmails.php  /home/wwwroot/index/web/Model/;
		\cp ./Controller/AMBmail.php  /home/wwwroot/index/web/Controller/;
		\cp ./View/AMBmail_list.php  /home/wwwroot/index/web/View/;

		# AMH 3.1&3.2
		if grep -q 'AMH 3\.' /home/wwwroot/index/web/View/index.php; then
			\cp ./View/backup_remote.php /home/wwwroot/index/web/View/;
			sed -i "/amh BRssh post/a\ \tamh module AMBmail-1.0 admin post,\$\{DoneBackup\} >\/dev\/null;" /root/amh/backup;
		else
			sed -i "/amh BRssh post/a\ \tamh module AMBmail-1.0 admin post,\$\{DoneBackup\};" /root/amh/backup;
		fi;

		mkdir -p /home/www;
		amh_module_status;
	fi;
}

#admin
function amh_module_admin()
{
	if amh_module_status ; then
		param_list=${1//,/ };
		set -- $param_list;
		action=$1;
		amh_file=$2;
		check_email=$2;

		[ "$action" == '' ] && echo "[Notice] AMBmail management, please select: (1~)" && \
		select action in 'post' 'check' 'eixt'; do break; done;
		[ "$action" == 'exit' ] && exit;

		IP=`ifconfig  | grep 'inet addr:'| grep -v '127.0.0.*' | cut -d: -f2 | awk '{ print $1}'`;
		MysqlPass=`cat /home/wwwroot/index/web/Amysql/Config.php | awk '{ FS="\047Password\047] = \047"; RS="\047;" } { print $2}' | sed '/^$/d'`;
		if [ "$action" == 'check' ]; then
			mail_title="AMBmail Test Email.";
			mail_body="server-ip: ${IP}\namh-backup-module: AMBmail";
			echo -e "$mail_body" | mutt -s "$mail_title" "$check_email" && echo "[OK] AMBmail-test ${check_email} success."; 
			exit;
		fi;

		if [ "$action" == 'post' ]; then
			[ "$amh_file" == '' ] && read -p "[Notice] please input AMH-Backup name:" amh_file;
			[ ! -f "/home/backup/${amh_file}" ] && echo '[Error] AMH-File not exists.' && exit 1;
			amh_backup_size=`ls -lh /home/backup/${amh_file} | awk '{print $5}'`;
			amh_backup_options='All-data';
			echo $amh_file | grep -q 'n-' && amh_backup_options='No-wwwroot-data';
			echo $amh_file | grep -q 'N-' && amh_backup_options='No-MySQL-data';
			amh_backup_sum=0;

			sql="SELECT remote_id , remote_ip , remote_user , remote_password , remote_path FROM amh.amh_backup_remote WHERE remote_type = 'AMBmail' AND remote_status = '1' ORDER BY remote_id ASC";
			mysql -uroot -p${MysqlPass} -B -N -e "${sql}"  | while read result; do
				set -- $result;
				ambmail_address=$2;
				ambmail_size='50996';
				echo $ambmail_address | egrep -q '@gmail|@yahoo' && ambmail_size='25396';
				[ "$ambmail_address" == '' ] && echo '[Error] Empty AMBmail-address.' && exit 1;
				
				rm -rf /home/backup/ambmail/;
				mkdir -p /home/backup/ambmail/;
				split -b ${ambmail_size}k -d -a 3 /home/backup/${amh_file} /home/backup/ambmail/${amh_file}.;
				amh_backup_sum=`ls /home/backup/ambmail/ | wc -l`;
				[ "$amh_backup_sum" == '1' ] && mv /home/backup/ambmail/${amh_file}.000 /home/backup/ambmail/${amh_file};

				cd /home/backup/ambmail/;
				mail_id=$RANDOM;
				mail_i=1;
				for ambmail_file in * ; do 
					mail_title="amh backup: ${amh_file} (Mail-ID:${mail_id})";
					mail_body="server-ip: ${IP}\namh-backup-name: ${amh_file}\namh-backup-size: ${amh_backup_size}\namh-backup-options: ${amh_backup_options}\namh-backup-No.: ${mail_i}/${amh_backup_sum}";
					echo -e "$mail_body" | mutt -s "$mail_title" "$ambmail_address" -a "$ambmail_file" && echo "[OK] AMBmail-post ${ambmail_file} success. (${ambmail_address})"; 
					mail_i=$[mail_i+1];
				done;
			done;
			rm -f /root/sent /home/www/sent;
			rm -rf /home/backup/ambmail/;
			exit;
		fi;
	else
		exit;
	fi;
}

#uninstall
function amh_module_uninstall()
{
	if amh_module_status ; then
		cd /usr/local/;
		rm -rf mutt-1.5.21 mutt-1.5.21.tar.gz;
		rm -f /home/wwwroot/index/web/Model/AMBmails.php /home/wwwroot/index/web/Controller/AMBmail.php /home/wwwroot/index/web/View/AMBmail_list.php;
		MysqlPass=`cat /home/wwwroot/index/web/Amysql/Config.php | awk '{ FS="\047Password\047] = \047"; RS="\047;" } { print $2}' | sed '/^$/d'`;
		mysql -uroot -p${MysqlPass} -B -N -e "use amh;DELETE FROM amh_backup_remote WHERE remote_type = 'AMBmail'";
		sed -i "/AMBmail-1.0/d" /root/amh/backup;
		echo '[OK] AMBmail Uninstall successful.';
	else
		exit;
	fi;
}

#status
function amh_module_status()
{
	if [ -d "/usr/local/mutt-1.5.21" ]; then
		echo '[OK] AMBmail is already installed.';
		return 0;
	else
		echo '[Notice] AMBmail is not installed.';
		return 1;
	fi;
}