#!/bin/bash
PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin;

#info
function amh_module_info()
{
		echo 'AMH-ModuleName: Gettext-5.3.22';
		echo 'AMH-ModuleDescription: PHP的Gettext扩展，Gettext用于系统的国际化(I18N)和本地化(L10N),可以在编译程序的时候使用本国语言支持(Native Language Support(NLS)),其可以使程序的输出使用用户设置的语言而不是英文.';
		echo 'AMH-ModuleButton: 安装/卸载';
		echo 'AMH-ModuleDate: 2013-04-09';
		echo 'AMH-ModuleAdmin: ';
		echo 'AMH-ModuleWebSite: http://amysql.com';
		echo 'AMH-ModuleScriptBy: Amysql';
}

#install
function amh_module_install()
{
		if amh_module_status ; then
				exit;
		else
				cd /usr/local/;
				wget http://code.amysql.com/files/gettext.tar.gz;
				tar -zxvf gettext.tar.gz;
				cd gettext;
				/usr/local/php/bin/phpize;
				./configure --with-php-config=/usr/local/php/bin/php-config;
				make && make install;
				
				
cat >> /etc/php.ini <<EOF
[Gettext] 
extension = /usr/local/php/lib/php/extensions/no-debug-non-zts-20090626/gettext.so
EOF
		amh php reload;
		amh_module_status;
		fi;
}

#admin
function amh_module_admin()
{
		if amh_module_status ; then
				echo '[OK] Gettext-5.3.22 No management options.';
		else
				exit;
		fi;
}

#uninstall
function amh_module_uninstall()
{
		if amh_module_status ; then

				cd /usr/local/;
				rm -rf gettext;
				rm -f gettext.tar.gz;
				rm -f /usr/local/php/lib/php/extensions/no-debug-non-zts-20090626/gettext.so;

				sed -i "/\[Gettext\]/d" /etc/php.ini;
				sed -i "/gettext.so/d" /etc/php.ini;
				amh php reload;
				echo '[OK] Gettext-5.3.22 Uninstall successful.';
		else
				exit;
		fi;
}

#status
function amh_module_status()
{
		if grep -q '\[Gettext\]' /etc/php.ini; then
				echo '[OK] Gettext-5.3.22 is already installed.';
				return 0;
		else
				echo '[Notice] Gettext-5.3.22 is not installed.';
				return 1;
		fi;
}

