#!/bin/bash
PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin;

#info
function amh_module_info()
{
	echo 'AMH-ModuleName: eAccelerator-0.9.6.1';
	echo 'AMH-ModuleDescription: eAccelerator是一个自由开放源码php加速器，优化和动态内容缓存，提高php脚本缓存性能，使得PHP脚本在编译的状态下，对服务器的开销几乎完全消除。 它还有对脚本优化作用，以加快其执行效率。使您的PHP程序代码执效率能提高1-10倍。';
	echo 'AMH-ModuleButton: 安装/卸载';
	echo 'AMH-ModuleDate: 2013-01-29';
	echo 'AMH-ModuleAdmin: ';
	echo 'AMH-ModuleWebSite: http://amysql.com';
	echo 'AMH-ModuleScriptBy: Amysql';
}

#install
function amh_module_install()
{
	if amh_module_status ; then
		exit;
	else
		cd /usr/local/;
		wget http://code.amysql.com/files/eaccelerator-0.9.6.1.zip;
		unzip eaccelerator-0.9.6.1.zip;
		cd eaccelerator-0.9.6.1;
		/usr/local/php/bin/phpize;
		./configure --enable-eaccelerator=shared --with-php-config=/usr/local/php/bin/php-config --with-eaccelerator-shared-memory;
		make && make install;
		mkdir /tmp/eaccelerator;
		chmod 777 /tmp/eaccelerator;

cat >> /etc/php.ini <<EOF
[eAccelerator]
zend_extension="/usr/local/php/lib/php/extensions/no-debug-non-zts-20090626/eaccelerator.so"
eaccelerator.shm_size="1"
eaccelerator.cache_dir="/tmp/eaccelerator"
eaccelerator.enable="1"
eaccelerator.optimizer="1"
eaccelerator.check_mtime="1"
eaccelerator.debug="0"
eaccelerator.filter=""
eaccelerator.shm_max="0"
eaccelerator.shm_ttl="3600"
eaccelerator.shm_prune_period="3600"
eaccelerator.shm_only="0"
eaccelerator.compress="1"
eaccelerator.compress_level="9"
eaccelerator.keys = "disk_only"
eaccelerator.sessions = "disk_only"
eaccelerator.content = "disk_only"
EOF
	amh php reload;
	amh_module_status;
	fi;
}

#admin 
function amh_module_admin()
{
	if amh_module_status ; then
		echo '[OK] eAccelerator-0.9.6.1 No management options.';
	else
		exit;
	fi;
}

#uninstall
function amh_module_uninstall()
{
	if amh_module_status ; then
		cd /usr/local/;
		rm -rf /tmp/eaccelerator;
		rm -rf eaccelerator-0.9.6.1.zip;
		rm -rf eaccelerator-0.9.6.1;
		rm -rf /usr/local/php/lib/php/extensions/no-debug-non-zts-20090626/eaccelerator.so;

		sed -i "/eaccelerator.*/d" /etc/php.ini;
		sed -i "/\[eAccelerator\]/d" /etc/php.ini;
		amh php reload;
		echo '[OK] eAccelerator-0.9.6.1 Uninstall successful.';
	else
		exit;
	fi;
}

#status
function amh_module_status()
{
	if grep -q '\[eAccelerator\]' /etc/php.ini; then
		echo '[OK] eAccelerator-0.9.6.1 is already installed.';
		return 0;
	else
		echo '[Notice] eAccelerator-0.9.6.1 is not installed.';
		return 1;
	fi;
}

