#!/bin/bash
PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin;


#info
function amh_module_info()
{
		echo 'AMH-ModuleName: limit_req2_nginx_module-1.2';
		echo 'AMH-ModuleDescription: nginx模块系列 - nginx限制请求处理频率的模块。典型应用：限制来自单个IP地址的请求处理频率。 限制的方法是通过一种“漏桶”的方法——固定每秒处理的请求数，推迟过多的请求处理。';
		echo 'AMH-ModuleButton: 安装/卸载';
		echo 'AMH-ModuleDate: 2013-05-26';
		echo 'AMH-ModuleAdmin: ';
		echo 'AMH-ModuleWebSite: http://www.lsanday.com';
		echo 'AMH-ModuleIco: http://amysql.com/View/images/amh_module/limit_req2_nginx_module.gif';
		echo 'AMH-ModuleScriptBy: Zeraba';
}

#upgrade
function upgrade()
{
	for module_name in `ls /root/amh/modules/ | grep 'limit_req2_nginx_module' | grep -v 'limit_req2_nginx_module-1.2'`; do
		amh module $module_name uninstall && amh module $module_name delete y;
	done;

	# /usr/local/nginx/sbin/nginx not found or error configure.
	nginx_configure='';
	[ -f /usr/local/nginx/sbin/nginx ] && nginx_configure=`/usr/local/nginx/sbin/nginx -V 2> /tmp/nginx_configure && cat /tmp/nginx_configure | grep 'configure arguments' | cut -d: -f2 && rm -f /tmp/nginx_configure`;
	if ! echo "$nginx_configure" | grep 'prefix=/usr/local/nginx' >/dev/null ; then
		amh host start;
		cd /usr/local/;
		wget http://code.amysql.com/files/nginx-1.2.9.tar.gz;
		tar -zxf nginx-1.2.9.tar.gz;
		cd nginx-1.2.9;
		./configure --prefix=/usr/local/nginx --user=www --group=www --with-http_ssl_module  --with-http_gzip_static_module --without-mail_pop3_module --without-mail_imap_module --without-mail_smtp_module --without-http_uwsgi_module --without-http_scgi_module ;
		Cpunum=`cat /proc/cpuinfo |grep 'processor'|wc -l`;
		make -j $Cpunum;
		make install;
		amh nginx reload;
	fi;
	/usr/local/nginx/sbin/nginx -t;
}


#install
function amh_module_install()
{
		if amh_module_status ; then
			exit;
		else
			upgrade;
			#install nginx module
			Cpunum=`cat /proc/cpuinfo |grep 'processor'|wc -l`;
			nginx_configure=`/usr/local/nginx/sbin/nginx -V 2> /tmp/nginx_configure && cat /tmp/nginx_configure | grep 'configure arguments' | cut -d: -f2 && rm -f /tmp/nginx_configure`;
			new_nginx_configure=$nginx_configure;
			if ! echo "$new_nginx_configure" | grep 'add-module=/usr/local/limit_req2_nginx_module' > /dev/null; then 
				new_nginx_configure="${new_nginx_configure} --add-module=/usr/local/limit_req2_nginx_module"
			fi;
				
			if [ "$nginx_configure" != "$new_nginx_configure" ]; then
				cd /usr/local/;
				wget https://github.com/monadbobo/limit_req2_nginx_module/archive/master.zip;
				unzip master*;
				mv limit_req2_nginx_module-master limit_req2_nginx_module; 
				wget http://code.amysql.com/files/nginx-1.2.9.tar.gz;
				tar -zxf nginx-1.2.9.tar.gz;

				cd nginx-1.2.9;
				./configure $new_nginx_configure;
				make -j $Cpunum;
				mv /usr/local/nginx/sbin/nginx /usr/local/nginx/sbin/nginx-old;
				\cp -a ./objs/nginx /usr/local/nginx/sbin/;
				kill -USR2 `cat /usr/local/nginx/logs/nginx.pid`;
				
				cd /usr/local/;
				rm -rf nginx-1.2.9.tar.gz nginx-1.2.9 /usr/local/nginx/sbin/nginx-old  master*;
			fi;

			\cp /root/amh/modules/limit_req2_nginx_module-1.2/cc.conf /usr/local/nginx/conf;
			\cp /root/amh/modules/limit_req2_nginx_module-1.2/refresh.html /home/wwwroot/index/etc/html/ErrorPages/;
					
			sed -i "s|Nginx.*<br />|Nginx 1.2.9 <br />|" /home/wwwroot/index/web/View/index.php;
			sed -i "/client_max_body_size/a\ \tlimit_req2_zone \$uri zone=three:3m rate=200r/s;"  /usr/local/nginx/conf/nginx.conf;
			sed -i "/client_max_body_size/a\ \tlimit_req2_zone \$binary_remote_addr \$uri zone=two:3m rate=20r/s;"  /usr/local/nginx/conf/nginx.conf;
			sed -i "/client_max_body_size/a\ \tlimit_req2_zone \$binary_remote_addr \$request_uri zone=one:3m rate=2r/s;"  /usr/local/nginx/conf/nginx.conf;
			sed -i "/fastcgi_param SCRIPT_FILENAME  \/web$domain$fastcgi_script_name/a\ \t\tlimit_req2 zone=one forbid_action=@rule1 nodelay;"  /usr/local/nginx/conf/nginx-host.conf;
			sed -i "/fastcgi_param SCRIPT_FILENAME  \/web$domain$fastcgi_script_name/a\ \t\tlimit_req2 zone=two burst=3 forbid_action=@rule2 nodelay;"  /usr/local/nginx/conf/nginx-host.conf;
			sed -i "/fastcgi_param SCRIPT_FILENAME  \/web$domain$fastcgi_script_name/a\ \t\tlimit_req2 zone=three forbid_action=@rule3 nodelay;"  /usr/local/nginx/conf/nginx-host.conf;
			sed -i "/include rewrite/a\ \tinclude cc.conf;"  /usr/local/nginx/conf/nginx-host.conf;
			
			#thanks @amysql with mod multi-conf
			for line in `ls /home/wwwroot/`; do
				conf_file="/usr/local/nginx/conf/vhost/$line.conf";
				[ -f "/usr/local/nginx/conf/vhost_stop/$line.conf" ] && conf_file="/usr/local/nginx/conf/vhost_stop/$line.conf";
				if [ -f $conf_file ]; then
					sed -i "/fastcgi_param SCRIPT_FILENAME/a\ \t\tlimit_req2 zone=one forbid_action=@rule1 nodelay;" $conf_file;
					sed -i "/fastcgi_param SCRIPT_FILENAME/a\ \t\tlimit_req2 zone=two burst=3 forbid_action=@rule2 nodelay;"  $conf_file;
					sed -i "/fastcgi_param SCRIPT_FILENAME/a\ \t\tlimit_req2 zone=three forbid_action=@rule3 nodelay;"  $conf_file;
					sed -i "/include rewrite/a\ \tinclude cc.conf;"  $conf_file;
					\cp /root/amh/modules/limit_req2_nginx_module-1.2/refresh.html /home/wwwroot/$line/web/ErrorPages/;
					# end
				fi;
			 done;
					
			#we can also use dir to help mod multi-index like below
			#for dir in /home/wwwroot/*/web/ErrorPages/ ; do
			#\cp /root/amh/modules/limit_req2_nginx_module-1.2/refresh.html $dir; 
			#done;
			
			touch /root/amh/modules/limit_req2_nginx_module-1.2/InstallComplete;
			sleep 3;
			kill -QUIT `cat /usr/local/nginx/logs/nginx.pid.oldbin`;
			
			amh nginx reload;
			amh_module_status;
		fi;
}

#admin
function amh_module_admin()
{
		if amh_module_status ; then
				echo '[OK] limit_req2_nginx_module-1.2 No management options.';
		else
				exit;
		fi;
}

#uninstall
function amh_module_uninstall()
{
		if amh_module_status ; then
				
			#uninstall nginx modules
			Cpunum=`cat /proc/cpuinfo |grep 'processor'|wc -l`;
			nginx_configure=`/usr/local/nginx/sbin/nginx -V 2> /tmp/nginx_configure && cat /tmp/nginx_configure | grep 'configure arguments' | cut -d: -f2 && rm -f /tmp/nginx_configure`;
			new_nginx_configure=$nginx_configure;
			if echo "$new_nginx_configure" | grep 'add-module=/usr/local/limit_req2_nginx_module' > /dev/null; then 
				new_nginx_configure=`echo $new_nginx_configure | sed "s|--add-module=/usr/local/limit_req2_nginx_module||"`;
			fi;

			if [ "$nginx_configure" != "$new_nginx_configure" ]; then
				cd /usr/local/;
				wget http://code.amysql.com/files/nginx-1.2.9.tar.gz;
				tar -zxf nginx-1.2.9.tar.gz;
				cd nginx-1.2.9;
				./configure $new_nginx_configure;
				make -j $Cpunum;
				mv /usr/local/nginx/sbin/nginx /usr/local/nginx/sbin/nginx-old;
				\cp -a ./objs/nginx /usr/local/nginx/sbin/;
				kill -USR2 `cat /usr/local/nginx/logs/nginx.pid`;
				cd /usr/local/;
				rm -rf nginx-1.2.9 nginx-1.2.9.tar.gz* /usr/local/nginx/sbin/nginx-old;
				kill -QUIT `cat /usr/local/nginx/logs/nginx.pid.oldbin`;
			fi;

			cd /usr/local/;
			rm -f /usr/local/nginx/conf/cc.conf /home/wwwroot/index/etc/html/ErrorPages/refresh.html;
			rm -rf limit_req2_nginx_module;
			
			sed -i "/limit_req2_zone/d" /usr/local/nginx/conf/nginx.conf;
			sed -i "/limit_req2/d" /usr/local/nginx/conf/nginx-host.conf;
			sed -i "/include cc.conf/d" /usr/local/nginx/conf/nginx-host.conf;
				
			for line in `ls /home/wwwroot/`; do
				conf_file="/usr/local/nginx/conf/vhost/$line.conf";
				[ -f "/usr/local/nginx/conf/vhost_stop/$line.conf" ] && conf_file="/usr/local/nginx/conf/vhost_stop/$line.conf";
				if [ -f $conf_file ]; then
					sed -i "/limit_req2/d" $conf_file;
					sed -i "/include cc.conf/d" $conf_file;
					rm -f /home/wwwroot/$line/web/ErrorPages/refresh.html;
				fi;
		        done;
				
			rm -f /root/amh/modules/limit_req2_nginx_module-1.2/InstallComplete;
			amh nginx reload;
			echo '[OK] limit_req2_nginx_module-1.2 Uninstall successful.';
		else
			exit;
		fi;
}

#status
function amh_module_status()
{
		if [ -f "/root/amh/modules/limit_req2_nginx_module-1.2/InstallComplete" ]; then
			echo '[OK] limit_req2_nginx_module-1.2 is already installed.';
			return 0;
		else
			echo '[Notice] limit_req2_nginx_module-1.2 is not installed.';
			return 1;
		fi;
}


