#!/bin/bash
PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin;

#info
function amh_module_info()
{
		echo 'AMH-ModuleName: Memcache-2.2.7-v2';
		echo 'AMH-ModuleDescription: v2更新版本，修复上一版本卸载文件残留问题。Memcache(客户端/php扩展)是一个可以应对任意多个连接，使用非阻塞的网络IO的缓存项目。由于它的工作机制是在内存中开辟一块空间，然后建立一个HashTable，Memcached便会自管理这些HashTable。';
		echo 'AMH-ModuleButton: 安装/卸载';
		echo 'AMH-ModuleDate: 2013-08-03';
		echo 'AMH-ModuleAdmin: ';
		echo 'AMH-ModuleWebSite: http://www.mf8.biz';
		echo 'AMH-MoudleScriptBy: MF8.biz';
}

#install
function amh_module_install()
{
	if amh_module_status ; then
		exit;
	else
		rm -rf /root/amh/modules/Memcache-2.2.7;
		cd /usr/local/;
		wget http://pecl.php.net/get/memcache-2.2.7.tgz;
		tar zxvf memcache-2.2.7.tgz;
		cd memcache-2.2.7;
		/usr/local/php/bin/phpize;
		./configure --with-php-config=/usr/local/php/bin/php-config;
		make && make install;

cat >> /etc/php.ini <<EOF
[memcache]
extension = /usr/local/php/lib/php/extensions/no-debug-non-zts-20090626/memcache.so
EOF
	amh php reload;
	amh_module_status;
	fi;
}

#admin 
function amh_module_admin()
{
	if amh_module_status ; then
		echo '[OK] Memcache-2.2.7-v2 No management options.';
	else
		exit;
	fi;
}

#uninstall
function amh_module_uninstall()
{
	if amh_module_status ; then
		rm -rf /root/amh/modules/Memcache-2.2.7;
		cd /usr/local/;
		rm -rf memcache-2.2.7.tgz;
		rm -rf memcache-2.2.7;
		rm -rf /usr/local/php/lib/php/extensions/no-debug-non-zts-20090626/memcache.so;

		sed -i "/\[memcache\]/d" /etc/php.ini;
		sed -i "/memcache\.so/d" /etc/php.ini;
		amh php reload;
		echo '[OK] Memcache-2.2.7-v2 Uninstall successful.';
	else
		exit;
	fi;
}

#status
function amh_module_status()
{
	if grep -q '\[memcache\]' /etc/php.ini; then
		echo '[OK] Memcache-2.2.7-v2 is already installed.';
		return 0;
	else
		echo '[Notice] Memcache-2.2.7-v2 is not installed.';
		return 1;
	fi;
}
