#!/bin/bash
PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin;

#info
function amh_module_info()
{
		echo 'AMH-ModuleName: ImageMagick ';
		echo 'AMH-ModuleDescription: ImageMagick是一套功能强大、稳定而且开源的工具集和开发包，可以用来读、写和处理超过89种基本格式的图片文件，包括流行的TIFF、JPEG、GIF、 PNG、PDF以及PhotoCD等格式。 ';
		echo 'AMH-ModuleButton: 安装/卸载';
		echo 'AMH-ModuleDate: 2013-09-04';
		echo 'AMH-ModuleAdmin:';
		echo 'AMH-ModuleWebSite: http://www.ixiqin.com';
		echo 'AMH-ModuleScriptBy: Xqgz';
		echo 'AMH-ModuleIco: http://amysql.com/View/images/amh_module/ImageMagick.gif';
}

#install
function amh_module_install()
{
		if amh_module_status ; then
			exit;
		else
			cd /usr/local/;
			 wget --no-check-certificate https://github.com/Codebyme/AMH-Debian-Install/blob/master/files/ImageMagick-6.7.1-2.tar.gz
			tar zxvf ImageMagick-6.7.1-2.tar.gz
			cd ImageMagick-6.7.1-2/
		       ./configure --prefix=/usr/local/imagemagick 
			make && make install
			cd ../
			wget http://pecl.php.net/get/imagick-3.0.1.tgz
			tar zxvf imagick-3.0.1.tgz
			cd imagick-3.0.1/
			/usr/local/php/bin/phpize
			./configure --with-php-config=/usr/local/php/bin/php-config --with-imagick=/usr/local/imagemagick
			make && make install
			cd ../
			echo 'extension = "imagick.so"' >>/etc/php.ini
			amh php reload;
 		 	amh_module_status;
		fi;
}

#admin
function amh_module_admin()
{
		if amh_module_status ; then
			echo '[OK] ImageMagick No management options.';
		else
			exit;
		fi;
}

#uninstall
function amh_module_uninstall()
{
		if amh_module_status ; then
			#cd /usr/local/ImageMagick-6.7.1-2/
			#make uninstall
			#cd /usr/local/imagick-3.0.1/
			#make uninstall
			rm -rf /usr/local/ImageMagick-6.7.1-2/
			rm -rf /usr/local/imagemagick/
			rm -rf /usr/local/imagick-3.0.1/
			rm -rf /usr/local/ImageMagick-6.7.1-2.tar.gz
			rm -rf /usr/local/imagick-3.0.1.tgz
			sed  -i /imagick.so/d /etc/php.ini
			amh php reload;
			echo '[OK] ImageMagick Uninstall successful.';
		else
			exit;
		fi;
}

#status
function amh_module_status()
{
		if [ -d "/usr/local/imagemagick" ]; then
			echo '[OK] ImageMagick is already installed.';
			return 0;
		else
			echo '[Notice] ImageMagick is not installed.';
			return 1;
		fi;
}
