#!/bin/bash
PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin;

#info
function amh_module_info()
{
		echo 'AMH-ModuleName: IMAP-5.3.27';
		echo 'AMH-ModuleDescription: PHP的IMAP扩展，安装IMAP可以使用相关函数通过这种协议从邮件服务器上获取邮件的信息、下载邮件等。IMAP与POP类似，都是一种邮件获取协议。但与POP不同的是IMAP客户端的操作都会反馈到服务器上，对邮件进行的操作，服务器上的邮件也会做相应的动作。';
		echo 'AMH-ModuleButton: 安装/卸载';
		echo 'AMH-ModuleDate: 2013-07-10';
		echo 'AMH-ModuleAdmin: ';
		echo 'AMH-ModuleWebSite: http://amysql.com';
		echo 'AMH-ModuleScriptBy: Amysql';
}

#install
function amh_module_install()
{
		if amh_module_status ; then
				exit;
		else
				if  egrep -i "centos" '/etc/issue'; then
					yum -y install libc-client-devel;
				else
					libc_name=`apt-cache search libc-client.*dev | awk '{print $1}'`;
					apt-get install -y $libc_name --force-yes;
				fi;
				cd /usr/local/;
				wget http://code.amysql.com/files/imap-5.3.27.tar.gz
				tar -zxvf imap-5.3.27.tar.gz;
				cd imap;
				/usr/local/php/bin/phpize;
				./configure --with-php-config=/usr/local/php/bin/php-config --with-kerberos --with-imap-ssl;
				make && make install;
				
				
cat >> /etc/php.ini <<EOF
[IMAP] 
extension = /usr/local/php/lib/php/extensions/no-debug-non-zts-20090626/imap.so
EOF
		amh php reload;
		amh_module_status;
		fi;
}

#admin
function amh_module_admin()
{
		if amh_module_status ; then
				echo '[OK] IMAP No management options.';
		else
				exit;
		fi;
}

#uninstall
function amh_module_uninstall()
{
		if amh_module_status ; then

				if  egrep -i "centos" '/etc/issue'; then
					yum -y remove libc-client-devel;
				else
					libc_name=`apt-cache search libc-client.*dev | awk '{print $1}'`;
					apt-get --purge remove $libc_name;
				fi;

				cd /usr/local/;
				rm -rf imap;
				rm -f imap-5.3.27.tar.gz;
				rm -f /usr/local/php/lib/php/extensions/no-debug-non-zts-20090626/imap.so;

				sed -i "/\[IMAP\]/d" /etc/php.ini;
				sed -i "/imap\.so/d" /etc/php.ini;
				amh php reload;
				echo '[OK] IMAP Uninstall successful.';
		else
				exit;
		fi;
}

#status
function amh_module_status()
{
		if grep -q '\[IMAP\]' /etc/php.ini; then
				echo '[OK] IMAP is already installed.';
				return 0;
		else
				echo '[Notice] IMAP is not installed.';
				return 1;
		fi;
}

