#!/bin/bash
PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin;

#info
function amh_module_info()
{
	    echo 'AMH-ModuleName: LanYing-VPN-1.0';
	    echo 'AMH-ModuleDescription: VPN代理服务器对用户的管理,支持PPTP和L2TP方式的VPN代理用户管理（增，删，改，查）';
	    echo 'AMH-ModuleButton: 安装/卸载';
	    echo 'AMH-ModuleDate: 2013-10-21';
	    echo 'AMH-ModuleAdmin: ./index.php?c=vpn';    
	    echo 'AMH-ModuleWebSite: http://www.lanyingblog.com';
	    echo 'AMH-ModuleIco: http://amysql.com/View/images/amh_module/LanYing-VPN.gif';
	    echo 'AMH-MoudleScriptBy: 蓝鹰';
}

#install
function amh_module_install()
{
    if amh_module_status ; then
    	exit;
    else    
		egrep -i "centos" /etc/issue && SysName='centos'
		if [ $SysName == 'centos' ]; then
			bash /root/amh/modules/LanYing-VPN-1.0/SH/install_c.sh;
		else 
			bash /root/amh/modules/LanYing-VPN-1.0/SH/install_d.sh;
		fi;
	        bash /root/amh/modules/LanYing-VPN-1.0/SH/install.sh;
	        echo "";
		amh_module_status;
    fi;
}

#admin
function amh_module_admin()
{
    if amh_module_status ; then
        action=$1;
		if [ "$action" == 'make' ]; then
	            MysqlPass=`cat /home/wwwroot/index/web/Amysql/Config.php | awk '{ FS="\047Password\047] = \047"; RS="\047;" } { print $2}' | sed '/^$/d'`;    
	            mysql -uroot -p${MysqlPass} amh -N -e "select vpn_user,vpn_pwd from module_vpn" > /root/amh/modules/LanYing-VPN-1.0/status;
	            cat /root/amh/modules/LanYing-VPN-1.0/status | sed 's/\s */ * /g' | sed 's/$/& */g' > /etc/ppp/chap-secrets;
		exit;
		fi;
    	echo '[OK] VPN-1.0 management options.';
    else
    	exit;
    fi;
}

#uninstall
function amh_module_uninstall()
{
    if amh_module_status ; then        
	egrep -i "centos" /etc/issue && SysName='centos';
	if [ $SysName == 'centos' ]; then
		bash /root/amh/modules/LanYing-VPN-1.0/SH/uninstall_c.sh;
	else 
		bash /root/amh/modules/LanYing-VPN-1.0/SH/uninstall_d.sh;
	fi;
        bash /root/amh/modules/LanYing-VPN-1.0/SH/uninstall.sh;
        echo '[OK] LanYing-VPN-1.0 Uninstall successful.';
    else
    	exit;
    fi;
}

#status
function amh_module_status()
{
    if [ -f "/root/amh/modules/LanYing-VPN-1.0/status" ]; then
            echo '[OK] LanYing-VPN-1.0 is already installed.';
            return 0;
    else
            echo '[Notice] LanYing-VPN-1.0 is not installed.';
            return 1;
    fi;
}

