#!/bin/bash
PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin;

#info
function amh_module_info()
{
		echo 'AMH-ModuleName: BBShijieSSL-1.1';
		echo 'AMH-ModuleDescription: BBShijieSSL AMH面板主机ssl(https)连接模块，为虚拟主机增加SSL功能，开启https访问，支持同一主机多个SSL站点。';
		echo 'AMH-ModuleButton: 安装/卸载';
		echo 'AMH-ModuleDate: 2013-08-27';
		echo 'AMH-ModuleAdmin: ./index.php?c=bbshijiessl&a=bbshijie_ssl';
		echo 'AMH-ModuleWebSite: http://www.baobaocool.com';
		echo 'AMH-ModuleIco: http://amysql.com/View/images/amh_module/BBShijieSSL.gif';
		echo 'AMH-ModuleScriptBy: BBShijie.';
}

#install
function amh_module_install()
{
                if amh_module_status ; then
                                exit;
                else
                                cd /root/amh/modules/BBShijieSSL-1.1;
                                \cp web/Controller/bbshijiessl.php  /home/wwwroot/index/web/Controller/;
                                #\cp web/Controller/bbshijiessl.un.php  /home/wwwroot/index/web/Controller/;
                                \cp web/View/bbshijiessl.php  /home/wwwroot/index/web/View/;

                                mkdir /usr/local/nginx/conf/ssl;
                                chown -R www:www /usr/local/nginx/conf/ssl;
                                sed -i "/'id' => 'php_setparam'/i\array('id' => 'bbshijie_ssl', 'url' => 'index.php?c=bbshijiessl&a=bbshijie_ssl', 'name' => 'SSL配置'),"  /home/wwwroot/index/web/View/category_list_data.php;
                                amh_module_status;
                fi;
}

#admin
function amh_module_admin()
{
		if amh_module_status ; then
			param_list=${1//,/ };
			set -- $param_list;
			action=$1;
			vhost=$2;
			status=$3;

			if [ "$action" == '' ]; then
				echo "[Notice] BBShijieSSL management, please select: (1~4)"
				select action in 'append' 'restore' 'check_tls' 'exit'; do
					break;
				done;
			fi;

			if [ "$action" == 'append' ]; then
				cat /usr/local/nginx/conf/ssl/tmp.conf > /usr/local/nginx/conf/vhost/$vhost.conf;
				exit;
			elif [ "$action" == 'restore' ]; then
				cat /usr/local/nginx/conf/ssl/tmp.conf > /usr/local/nginx/conf/vhost$status/$vhost.conf;
				exit;
			elif [ "$action" == 'check_tls' ]; then
				/usr/local/nginx/sbin/nginx -V 2>&1 > /tmp/nginx_check_tls && cat /tmp/nginx_check_tls;
				exit;
			else
				amh module BBShijieSSL-1.1 admin;
				exit;
			fi;
		else
				exit;
		fi;
}

#uninstall
function amh_module_uninstall()
{
                if amh_module_status ; then
				#restore all ssl vhosts to normal
				/usr/local/php/bin/php -q "/root/amh/modules/BBShijieSSL-1.1/web/Controller/bbshijiessl.un.php";
				sed -i "/bbshijie_ssl/d" /home/wwwroot/index/web/View/category_list_data.php;

                                rm -f /home/wwwroot/index/web/Controller/bbshijiessl.php /home/wwwroot/index/web/View/bbshijiessl.php;
                                rm -rf /usr/local/nginx/conf/ssl/;
                                echo '[OK] BBShijieSSL Uninstall successful.';
                else
                                exit;
                fi;
}

#status
function amh_module_status()
{
                if [ -f "/home/wwwroot/index/web/Controller/bbshijiessl.php" ]; then
                                echo '[OK] BBShijieSSL is already installed.';
                                return 0;
                else
                                echo '[Notice] BBShijieSSL is not installed.';
                                return 1;
                fi;
}
