#!/bin/bash
PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin;

#info
function amh_module_info()
{
		echo 'AMH-ModuleName: Zend_Guard_Loader';
		echo 'AMH-ModuleDescription: Zend Guard不仅可以实现对PHP应用的脚本进行加密保护和对PHP应用的产品进行商业许可证管理，还可以为许多软件生产商、IT服务提供商提供完善的加密和安全的产品发布系统。';
		echo 'AMH-ModuleButton: 安装/卸载';
		echo 'AMH-ModuleDate: 2013-02-01';
		echo 'AMH-ModuleAdmin: ';
		echo 'AMH-ModuleWebSite: http://amysql.com';
		echo 'AMH-ModuleScriptBy: Amysql';
}

#install
function amh_module_install()
{
		if amh_module_status ; then
				exit;
		else
				cd /usr/local/;
				if [ `getconf WORD_BIT` == '32' ] && [ `getconf LONG_BIT` == '64' ]; then
					wget http://code.amysql.com/files/ZendGuardLoader-php-5.3-linux-glibc23-x86_64.tar.gz;
					tar -zxvf ZendGuardLoader-php-5.3-linux-glibc23-x86_64.tar.gz;
					mv ZendGuardLoader-php-5.3-linux-glibc23-x86_64 Zend_Guard_Loader;
				else
					wget http://code.amysql.com/files/ZendGuardLoader-php-5.3-linux-glibc23-i386.tar.gz;
					tar -zxvf ZendGuardLoader-php-5.3-linux-glibc23-i386.tar.gz;
					mv ZendGuardLoader-php-5.3-linux-glibc23-i386 Zend_Guard_Loader;
				fi;
				
cat >> /etc/php.ini <<EOF
[Zend_Guard_Loader] 
zend_extension = /usr/local/Zend_Guard_Loader/php-5.3.x/ZendGuardLoader.so
zend_loader.enable = 1
EOF
		amh php reload;
		amh_module_status;
		fi;
}

#admin
function amh_module_admin()
{
		if amh_module_status ; then
				echo '[OK] Zend_Guard_Loader No management options.';
		else
				exit;
		fi;
}

#uninstall
function amh_module_uninstall()
{
		if amh_module_status ; then
				cd /usr/local/;
				if [ `getconf WORD_BIT` == '32' ] && [ `getconf LONG_BIT` == '64' ]; then
					rm -rf ZendGuardLoader-php-5.3-linux-glibc23-x86_64.tar.gz;
				else
					rm -rf ZendGuardLoader-php-5.3-linux-glibc23-i386.tar.gz;
				fi;
				rm -rf /usr/local/Zend_Guard_Loader/;


				sed -i "/Zend_Guard_Loader/d" /etc/php.ini;
				sed -i "/zend_loader/d" /etc/php.ini;
				amh php reload;
				echo '[OK] Zend_Guard_Loader Uninstall successful.';
		else
				exit;
		fi;
}

#status
function amh_module_status()
{
		if grep -q '\[Zend_Guard_Loader\]' /etc/php.ini; then
				echo '[OK] Zend_Guard_Loader is already installed.';
				return 0;
		else
				echo '[Notice] Zend_Guard_Loader is not installed.';
				return 1;
		fi;
}

