#!/bin/bash
PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin;

#info
function amh_module_info()
{
		echo 'AMH-ModuleName: IonCube_loaders';
		echo 'AMH-ModuleDescription: IonCube是用来加密PHP的工具。ionCube Encoder可以把PHP源代码转换成ByteCode。进行加密授权处理后的PHP代码就不在开源了，必须使用ionCube loader才可以执行加密过的PHP代码。(注意本模块可能与Zend_Guard_Loader不兼容。)';
		echo 'AMH-ModuleButton: 安装/卸载';
		echo 'AMH-ModuleDate: 2013-02-01';
		echo 'AMH-ModuleAdmin: ';
		echo 'AMH-ModuleWebSite: http://amysql.com';
		echo 'AMH-ModuleScriptBy: Amysql';
}

#install
function amh_module_install()
{
		if amh_module_status ; then
				exit;
		else
			if grep -q '\[Zend_Guard_Loader\]' /etc/php.ini; then
				echo '[Warning] Zend_Guard_Loader and IonCube_loaders conflict, Setup exit.';
				exit 1;
			fi;
			cd /usr/local/;
			if [ `getconf WORD_BIT` == '32' ] && [ `getconf LONG_BIT` == '64' ]; then
				wget --no-check-certificate https://github.com/Codebyme/AMH-Debian-Install/blob/master/files/ioncube_loaders_lin_x86-64.tar.gz;
				tar -zxvf ioncube_loaders_lin_x86-64.tar.gz
			else
				wget --no-check-certificate https://github.com/Codebyme/AMH-Debian-Install/blob/master/files/ioncube_loaders_lin_x86.tar.gz
				tar -zxvf ioncube_loaders_lin_x86.tar.gz
			fi;
				
cat >> /etc/php.ini <<EOF
[ioncube_loader]
zend_extension="/usr/local/ioncube/ioncube_loader_lin_5.3.so"
EOF
		amh php reload;
		amh_module_status;
		fi;
}

#admin
function amh_module_admin()
{
		if amh_module_status ; then
				echo '[OK] IonCube_loaders No management options.';
		else
				exit;
		fi;
}

#uninstall
function amh_module_uninstall()
{
		if amh_module_status ; then
				cd /usr/local/;
				if [ `getconf WORD_BIT` == '32' ] && [ `getconf LONG_BIT` == '64' ]; then
					rm -rf ioncube_loaders_lin_x86-64.tar.gz
				else
					rm -rf ioncube_loaders_lin_x86.tar.gz
				fi;
				rm -rf /usr/local/ioncube/;


				sed -i "/ioncube_loader/d" /etc/php.ini;
				amh php reload;
				echo '[OK] IonCube_loaders Uninstall successful.';
		else
				exit;
		fi;
}

#status
function amh_module_status()
{
		if grep -q '\[ioncube_loader\]' /etc/php.ini; then
				echo '[OK] IonCube_loaders is already installed.';
				return 0;
		else
				echo '[Notice] IonCube_loaders is not installed.';
				return 1;
		fi;
}

