#!/bin/bash
PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin;

#info
function amh_module_info()
{
		echo 'AMH-ModuleName: phpMyAdmin-3.5.8';
		echo 'AMH-ModuleDescription: 最新版本phpMyAdmin-3.5.8。面板数据库默认管理系统是由Amysql自主开发的AMS MySQL管理系统，建库建表查看修改删除数据、权限管理等能满足日常操作。部分功能目前还没有phpmyadmin强大，如另需使用phpmyadmin请安装。';
		echo 'AMH-ModuleButton: 安装/卸载';
		echo 'AMH-ModuleDate: 2013-04-12';
		echo 'AMH-ModuleAdmin: ./phpmyadmin358_amh/index.php';
		echo 'AMH-ModuleWebSite: http://amysql.com';
		echo 'AMH-ModuleScriptBy: Amysql';
}

#install
function amh_module_install()
{
		if amh_module_status ; then
				exit;
		else
				cd /usr/local/;
				wget http://code.amysql.com/files/phpMyAdmin-3.5.8-all-languages.zip;
				unzip phpMyAdmin-3.5.8-all-languages.zip;
				mv phpMyAdmin-3.5.8-all-languages /home/wwwroot/index/web/phpmyadmin358_amh;
				sed -i "/ams=index/a\<input type=\"button\" value=\"phpMyAdmin-3.5.8\" onclick=\"WindowOpen('./phpmyadmin358_amh/index.php');\"/>"  /home/wwwroot/index/web/View/mysql.php;
				amh_module_status;
		fi;
}

#admin
function amh_module_admin()
{
		if amh_module_status ; then
				echo '[OK] phpMyAdmin-3.5.8 Management:  http://ip:8888/phpmyadmin358_amh/ ';
		else
				exit;
		fi;
}

#uninstall
function amh_module_uninstall()
{
		if amh_module_status ; then

				rm -rf /home/wwwroot/index/web/phpmyadmin358_amh;
				rm -f /usr/local/phpMyAdmin-3.5.8-all-languages.zip;
				sed -i "/phpMyAdmin-3.5.8/d" /home/wwwroot/index/web/View/mysql.php;
				echo '[OK] phpMyAdmin-3.5.8 Uninstall successful.';
		else
				exit;
		fi;
}

#status
function amh_module_status()
{
		if [ -d "/home/wwwroot/index/web/phpmyadmin358_amh" ]; then
				echo '[OK] phpMyAdmin-3.5.8 is already installed.';
				return 0;
		else
				echo '[Notice] phpMyAdmin-3.5.8 is not installed.';
				return 1;
		fi;
}

