#!/bin/bash
PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin;

#info
function amh_module_info()
{
		echo 'AMH-ModuleName: MySQLi';
		echo 'AMH-ModuleDescription: MySQLi扩展对象主要控制PHP和MySQL数据库服务器之间的连接、选择数据库、向MySQL服务器发送SQL语句，以及设置字符集等，这些任务都是通过该类中声明的构造方法、成员方法和成员属性完成的。';
		echo 'AMH-ModuleButton: 安装/卸载';
		echo 'AMH-ModuleDate: 2013-02-01';
		echo 'AMH-ModuleAdmin: ';
		echo 'AMH-ModuleWebSite: http://amysql.com';
		echo 'AMH-ModuleScriptBy: Amysql';
}

#install
function amh_module_install()
{
		if amh_module_status ; then
				exit;
		else
				cd /usr/local/;
				wget http://code.amysql.com/files/mysqli.tar.gz;
				tar -zxvf mysqli.tar.gz;
				cd mysqli;
				/usr/local/php/bin/phpize;
				./configure --with-php-config=/usr/local/php/bin/php-config --with-mysqli=/usr/local/mysql/bin/mysql_config;
				make && make install;
				
				
cat >> /etc/php.ini <<EOF
[mysqli.so] 
extension = /usr/local/php/lib/php/extensions/no-debug-non-zts-20090626/mysqli.so
EOF
		amh php reload;
		amh_module_status;
		fi;
}

#admin
function amh_module_admin()
{
		if amh_module_status ; then
				echo '[OK] MySQLi No management options.';
		else
				exit;
		fi;
}

#uninstall
function amh_module_uninstall()
{
		if amh_module_status ; then
				cd /usr/local/;
				rm -rf mysqli;
				rm -rf mysqli.tar.gz;
				rm /usr/local/php/lib/php/extensions/no-debug-non-zts-20090626/mysqli.so;

				sed -i "/mysqli\.so/d" /etc/php.ini;
				amh php reload;
				echo '[OK] MySQLi Uninstall successful.';
		else
				exit;
		fi;
}

#status
function amh_module_status()
{
		if grep -q '\[mysqli\.so\]' /etc/php.ini; then
				echo '[OK] MySQLi is already installed.';
				return 0;
		else
				echo '[Notice] MySQLi is not installed.';
				return 1;
		fi;
}

