#!/bin/bash
PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin;

#info
function amh_module_info()
{
		echo 'AMH-ModuleName: YaHeiPHP-1.0';
		echo 'AMH-ModuleDescription: AMH面板雅黑PHP探针模块，探针可以实时查看服务器硬盘资源、内存占用、网卡流量、系统负载、服务器时间等信息，1秒钟刷新一次。 以及包括服务器IP地址，Web服务器环境监测，php等信息。(Yahei.Net)';
		echo 'AMH-ModuleButton: 安装/卸载';
		echo 'AMH-ModuleDate: 2013-05-22';
		echo 'AMH-ModuleAdmin: ./index.php?c=yaheiphp';
		echo 'AMH-ModuleWebSite: http://amysql.com';
		echo 'AMH-ModuleScriptBy: Amysql.';
}

#install
function amh_module_install()
{
		if amh_module_status ; then
				exit;
		else
				cd /root/amh/modules/YaHeiPHP-1.0;
				\cp ./Controller/yaheiphp.php  /home/wwwroot/index/web/Controller/;
				\cp ./View/yaheiphp.php  /home/wwwroot/index/web/View/;

				sed -i "/footer.php/i\<script>G('phpinfo').appendChild( C('a', {'id':'YaHeiPHP-1.0', 'innerHTML':'PHP探针', 'href':'/index.php?c=yaheiphp'}) );<\/script>"  /home/wwwroot/index/web/View/index.php;
				amh_module_status;
		fi;
}

#admin
function amh_module_admin()
{
		if amh_module_status ; then
				echo '[OK] YaHeiPHP-1.0 No management options.';
		else
				exit;
		fi;
}

#uninstall
function amh_module_uninstall()
{
		if amh_module_status ; then
				rm -f /home/wwwroot/index/web/Controller/yaheiphp.php /home/wwwroot/index/web/View/yaheiphp.php;
				sed -i "/YaHeiPHP-1.0/d" /home/wwwroot/index/web/View/index.php;
				echo '[OK] YaHeiPHP-1.0 Uninstall successful.';
		else
				exit;
		fi;
}

#status
function amh_module_status()
{
		if [ -f "/home/wwwroot/index/web/Controller/yaheiphp.php" ]; then
				echo '[OK] YaHeiPHP-1.0 is already installed.';
				return 0;
		else
				echo '[Notice] YaHeiPHP-1.0 is not installed.';
				return 1;
		fi;
}
