#!/bin/bash
PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin;

#info
function amh_module_info()
{
		echo 'AMH-ModuleName: AMUsers-1.0';
		echo 'AMH-ModuleDescription: AMUsers是基于AMH面板的多用户管理模块。 模块拥有用户管理、用户权限设置、管理等功能，应用AMUsers您可按需求在线设计需要的面板功能， AMH面板基础的所有功能都可实现，后期发布的AMH模块，用户也可轻松整合到AMUsers。默认管理员账号： 账号 admin 密码 amysql ';
		echo 'AMH-ModuleButton: 安装/卸载';
		echo 'AMH-ModuleDate: 2013-10-17';
		echo 'AMH-ModuleAdmin: ./AMUsers-1.0/';
		echo 'AMH-ModuleWebSite: http://amysql.com';
		echo 'AMH-ModuleIco: http://amysql.com/View/images/amh_module/AMUsers.gif';
		echo 'AMH-ModuleScriptBy: Amysql';
}

#install
function amh_module_install()
{
		if amh_module_status ; then
			exit;
		else
			cd /usr/local/;
			MysqlPass=`cat /home/wwwroot/index/web/Amysql/Config.php | awk '{ FS="\047Password\047] = \047"; RS="\047;" } { print $2}' | sed '/^$/d'`;
			wget http://code.amysql.com/files/AMUsers-1.0.zip;
			unzip AMUsers-1.0.zip;
			mv AMUsers-1.0 /home/wwwroot/index/web;
			mysql -uroot -p$MysqlPass < ./AMUsers.sql;
			rm -f AMUsers-1.0.zip AMUsers.sql;
			touch /home/wwwroot/index/web/AMUsers-1.0/View/index_templet.php;
			chown www:www /home/wwwroot/index/web/AMUsers-1.0/View/index_templet.php;

			wget http://code.amysql.com/files/AMUsers-host-ftp-pass.sql;
			mysql -uroot -p$MysqlPass < ./AMUsers-host-ftp-pass.sql;
			rm -f AMUsers-host-ftp-pass.sql;

			amh_module_status;
		fi;
}

#admin
function amh_module_admin()
{
		if amh_module_status ; then
			echo '[OK] AMUsers-1.0 Management:  http://ip:8888/AMUsers-1.0/ ';
		else
			exit;
		fi;
}

#uninstall
function amh_module_uninstall()
{
		if amh_module_status ; then
			MysqlPass=`cat /home/wwwroot/index/web/Amysql/Config.php | awk '{ FS="\047Password\047] = \047"; RS="\047;" } { print $2}' | sed '/^$/d'`;
			rm -rf /home/wwwroot/index/web/AMUsers-1.0;
			sql='DROP TABLE amh.module_amusers_grant;DROP TABLE amh.module_amusers_user_product;DROP TABLE amh.module_amusers_controller;DROP TABLE amh.module_amusers_item;DROP TABLE amh.module_amusers_item_property;DROP TABLE amh.module_amusers_item_type;DROP TABLE amh.module_amusers_product;DROP TABLE amh.module_amusers_group;DROP TABLE amh.module_amusers_user;';
			mysql -uroot -p${MysqlPass} -B -N -e "$sql";
			echo '[OK] AMUsers-1.0 Uninstall successful.';
		else
			exit;
		fi;
}

#status
function amh_module_status()
{
		if [ -d "/home/wwwroot/index/web/AMUsers-1.0/" ]; then
			echo '[OK] AMUsers-1.0 is already installed.';
			return 0;
		else
			echo '[Notice] AMUsers-1.0 is not installed.';
			return 1;
		fi;
}
