#!/bin/bash
PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin;

#info
function amh_module_info()
{
	echo 'AMH-ModuleName: PDO_MYSQL-1.0.2';
	echo 'AMH-ModuleDescription: PDO扩展为PHP访问数据库定义了一个轻量级的、一致性的接口，它提供了一个数据访问抽象层，这样，无论使用什么数据库，都可以通过一致的函数执行查询和获取数据。';
	echo 'AMH-ModuleButton: 安装/卸载';
	echo 'AMH-ModuleDate: 2013-1-31';
	echo 'AMH-ModuleAdmin: ';
	echo 'AMH-ModuleWebSite: http://amysql.com';
	echo 'AMH-ModuleScriptBy: Amysql';
}

#install
function amh_module_install()
{
	if amh_module_status ; then
		exit;
	else
		cd /usr/local/;
		wget http://code.amysql.com/files/PDO_MYSQL-1.0.2.tgz;
		tar -zxvf PDO_MYSQL-1.0.2.tgz;
		cd PDO_MYSQL-1.0.2;
		/usr/local/php/bin/phpize;
		./configure --with-php-config=/usr/local/php/bin/php-config -with-pdo-mysql=/usr/local/mysql/bin/mysql_config;
		make && make install;

cat >> /etc/php.ini <<EOF
[pdo_mysql]
extension = /usr/local/php/lib/php/extensions/no-debug-non-zts-20090626/pdo_mysql.so
EOF
	amh php reload;
	amh_module_status;
	fi;
}

#admin 
function amh_module_admin()
{
	if amh_module_status ; then
		echo '[OK] PDO_MYSQL-1.0.2 No management options.';
	else
		exit;
	fi;
}

#uninstall
function amh_module_uninstall()
{
	if amh_module_status ; then
		cd /usr/local/;
		rm -rf PDO_MYSQL-1.0.2.tgz;
		rm -rf PDO_MYSQL-1.0.2;
		rm -rf /usr/local/php/lib/php/extensions/no-debug-non-zts-20090626/pdo_mysql.so;

		sed -i "/pdo_mysql\.so/d" /etc/php.ini;
		sed -i "/\[pdo_mysql]/d" /etc/php.ini;
		amh php reload;
		echo '[OK] PDO_MYSQL-1.0.2 Uninstall successful.';
	else
		exit;
	fi;
}

#status
function amh_module_status()
{
	if grep -q '\[pdo_mysql\]' /etc/php.ini; then
		echo '[OK] PDO_MYSQL-1.0.2 is already installed.';
		return 0;
	else
		echo '[Notice] PDO_MYSQL-1.0.2 is not installed.';
		return 1;
	fi;
}

